#10 deploy multiple instances
PowereX-jsa/pwx-actions pull request #11
Opened 2024-12-17 10:14 UTC by rastoliska25

2024-12-20 12:56 UTC, rastoliska25 commented
odskusane na id-trading apke -> nasadilo saa naraz viacero schedulovanych taskov

2024-12-20 12:56 UTC, rastoliska25 commented
omylom som pushol do mastra deploy-multiple-scheduled-instances.yml -> zabudol som ze tu nieje main chraneny, preto subor mazem

2024-12-20 12:57 UTC, rastoliska25 commented
omylom som pushol do mastra deploy-multiple-scheduled-instances.yml -> zabudol som ze tu nieje master chraneny, preto subor mazem

2025-01-07 09:20 UTC, styko requested changes

2025-01-07 09:20 UTC, styko commented on .github/workflows/deploy-multiple-scheduled-tasks.yml
> +          TARGETS=$(jq -c '.Targets' new-target.json)
este by som zalogoval updatnutny target.json

2025-01-07 11:45 UTC, styko approved these changes

2025-01-07 11:46 UTC, merged